#!/usr/bin/env python3
"""
School Email Digest — daily briefing-style summary of school emails.

Fetches school emails, sends them all to Claude in one batch, and delivers
a concise markdown briefing via email.

Usage:
    python3 digest.py                # Send daily digest
    python3 digest.py --dry-run      # Preview without sending
"""

import argparse
import html
import re
import sys
from datetime import datetime

from config import Config
from gmail_client import GmailClient
from summarizer import Summarizer


def _inline_markdown(text: str) -> str:
    """Convert inline markdown (bold, links) to HTML. Input should NOT be escaped yet."""
    # Links first: [text](url) -> <a>text</a>
    # We extract links, escape everything else, then put links back
    link_pattern = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')
    parts = []
    last_end = 0
    for match in link_pattern.finditer(text):
        # Escape text before this link
        parts.append(html.escape(text[last_end:match.start()]))
        link_text = html.escape(match.group(1))
        url = match.group(2)
        parts.append(f'<a href="{url}" style="color:#1a73e8;text-decoration:none;">{link_text}</a>')
        last_end = match.end()
    parts.append(html.escape(text[last_end:]))
    result = "".join(parts)

    # Bold: **text** -> <strong>text</strong>
    result = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", result)
    return result


def _markdown_to_html(md: str) -> str:
    """Convert simple markdown to HTML for email rendering.

    Handles: ## headers, **bold**, [links](url), - bullets, paragraphs.
    Keeps it simple — no external dependencies needed.
    """
    lines = md.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Close list if we're no longer in one
        if in_list and not stripped.startswith("- "):
            html_lines.append("</ul>")
            in_list = False

        if not stripped:
            html_lines.append("<br>")
            continue

        # Headers
        if stripped.startswith("## "):
            text = html.escape(stripped[3:])
            html_lines.append(
                f'<h2 style="margin:18px 0 8px 0;font-size:17px;color:#1a1a1a;'
                f'border-bottom:1px solid #eee;padding-bottom:4px;">{text}</h2>'
            )
            continue

        # Bullet items
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append(
                    '<ul style="margin:4px 0;padding-left:20px;font-size:14px;'
                    'line-height:1.7;color:#333;">'
                )
                in_list = True
            item_html = _inline_markdown(stripped[2:])
            html_lines.append(f"<li style='margin-bottom:4px;'>{item_html}</li>")
            continue

        # Regular paragraph
        text = _inline_markdown(stripped)
        html_lines.append(f'<p style="margin:6px 0;font-size:14px;color:#333;line-height:1.6;">{text}</p>')

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _feedback_mailto(date_str: str) -> str:
    """Build a mailto: link that pre-populates a feedback email."""
    from urllib.parse import quote
    subject = quote(f"[SchoolSkim Feedback] Digest for {date_str}")
    body = quote(
        "What was missing or wrong in today's digest?\n\n"
        "[ ] Something important was left out\n"
        "[ ] Something unimportant was included\n"
        "[ ] Summary was unclear or inaccurate\n"
        "[ ] Other\n\n"
        "Details:\n"
    )
    return f"mailto:hello@schoolskim.com?subject={subject}&body={body}"


def build_html(digest_markdown: str) -> str:
    """Wrap Claude's markdown digest in a clean HTML email template."""
    now = datetime.now()
    date_str = now.strftime('%A, %B %d, %Y')
    content_html = _markdown_to_html(digest_markdown)
    feedback_url = _feedback_mailto(date_str)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,
             'Segoe UI',Roboto,sans-serif;">
<div style="max-width:640px;margin:0 auto;padding:20px;">

    <div style="background:#1a73e8;color:#fff;border-radius:12px 12px 0 0;padding:20px 24px;">
        <h1 style="margin:0;font-size:22px;">Daily School Digest</h1>
        <div style="font-size:13px;opacity:0.85;margin-top:4px;">
            {date_str}
        </div>
    </div>

    <div style="background:#fff;border-radius:0 0 12px 12px;padding:20px 24px;
                border:1px solid #e0e0e0;border-top:none;">
        {content_html}

        <div style="text-align:center;font-size:12px;color:#aaa;margin-top:20px;
                    padding-top:16px;border-top:1px solid #eee;">
            Generated by SchoolSkim &middot;
            <a href="{feedback_url}"
               style="color:#aaa;text-decoration:underline;">Something missing or wrong?</a>
        </div>
    </div>

</div>
</body>
</html>"""


def run_digest(dry_run: bool = False):
    """Generate and optionally send a daily digest email."""
    print("Daily School Digest\n")
    print("   Looking back 28 hours...")

    if not Config.ANTHROPIC_API_KEY:
        print("ANTHROPIC_API_KEY not set.")
        sys.exit(1)

    # 1. Fetch school emails
    print("Connecting to Gmail...")
    gmail = GmailClient()
    gmail.authenticate()

    query = Config.digest_query(hours_back=28)
    print(f"Query: {query[:100]}...")
    emails = gmail.fetch_emails(query, max_results=100)
    print(f"   Found {len(emails)} email(s).")

    if not emails:
        print("No school emails today.")
        return

    # 2. Batch summarize
    print(f"\nSummarizing {len(emails)} email(s)...")
    summarizer = Summarizer()
    digest_md = summarizer.summarize(emails)

    # 3. Build HTML
    print("\nBuilding HTML...")
    email_html = build_html(digest_md)

    if dry_run:
        from pathlib import Path
        preview_path = Path(__file__).parent / "digest_preview.html"
        preview_path.write_text(email_html)
        print(f"\nDry run — preview saved to: {preview_path}")
        print(f"Open it in a browser to see the digest.\n")
        print("--- Digest content ---")
        print(digest_md)
        print("---")
        return

    # 4. Send
    if not Config.EMAIL_TO:
        print("EMAIL_TO not set.")
        sys.exit(1)

    subject = f"🎒 Daily School Digest — {datetime.now().strftime('%b %d, %Y')}"
    print(f"\nSending to {Config.EMAIL_TO}...")
    gmail.send_html_email(Config.EMAIL_TO, subject, email_html)
    print("Sent!")


def main():
    parser = argparse.ArgumentParser(description="School email digest generator.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview digest without sending email.")
    args = parser.parse_args()

    run_digest(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
