import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service - SchoolSkim",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Terms of Service
          </h1>
          <p className="text-sm text-gray-400 mb-8">
            Effective April 1, 2026
          </p>

          <div className="space-y-8 text-gray-700 text-[15px] leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                1. Service Description
              </h2>
              <p>
                SchoolSkim is a subscription service that summarizes school
                emails into a daily digest. You forward emails from your
                child&apos;s school to a unique address we provide, and we
                deliver an AI-generated summary to your inbox each evening.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                2. Subscription &amp; Billing
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  SchoolSkim costs <strong>$3 per month</strong> after a{" "}
                  <strong>14-day free trial</strong>.
                </li>
                <li>
                  Your subscription renews automatically each month unless you
                  cancel.
                </li>
                <li>
                  You can cancel anytime through Stripe&apos;s customer portal
                  or by emailing{" "}
                  <a
                    href="mailto:hello@schoolskim.com"
                    className="text-brand hover:underline"
                  >
                    hello@schoolskim.com
                  </a>
                  .
                </li>
                <li>
                  Refunds are available for the current billing period if you
                  contact us within 7 days of being charged.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                3. What You&apos;re Responsible For
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  Setting up email forwarding from your school to your
                  SchoolSkim address.
                </li>
                <li>
                  Providing accurate information about your children so
                  digests can be organized correctly.
                </li>
                <li>
                  Not forwarding emails that contain sensitive information
                  beyond typical school communications (e.g., medical records,
                  legal documents).
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                4. AI-Generated Content
              </h2>
              <p>
                Digests are generated by AI (Anthropic&apos;s Claude) and may
                occasionally contain errors, miss details, or misattribute
                information to the wrong child or school. SchoolSkim is a
                convenience tool, not a replacement for reading critical school
                communications directly. Always verify important action items
                (deadlines, medical forms, safety alerts) against the original
                email.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                5. Service Availability
              </h2>
              <p>
                We aim to deliver your digest every day, but we do not guarantee
                uninterrupted service. Outages may occur due to email provider
                issues, AWS infrastructure, or AI service availability. We will
                make reasonable efforts to restore service promptly but are not
                liable for missed or delayed digests.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                6. Limitation of Liability
              </h2>
              <p>
                SchoolSkim is provided &quot;as is&quot; without warranties of
                any kind. To the maximum extent permitted by law, SchoolSkim
                shall not be liable for any indirect, incidental, or
                consequential damages arising from your use of the service,
                including but not limited to missed school events, incorrect
                summaries, or data loss.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                7. Account Termination
              </h2>
              <p>
                We reserve the right to suspend or terminate your account if you
                misuse the service, including but not limited to: forwarding
                non-school emails in bulk, using the service for commercial
                purposes, or attempting to abuse our infrastructure.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                8. Changes to These Terms
              </h2>
              <p>
                We may update these terms from time to time. If we make
                significant changes, we&apos;ll notify you by email. Continued
                use of the service after changes constitutes acceptance of the
                updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                9. Contact
              </h2>
              <p>
                Questions about these terms? Email us at{" "}
                <a
                  href="mailto:hello@schoolskim.com"
                  className="text-brand hover:underline"
                >
                  hello@schoolskim.com
                </a>
                .
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-gray-100">
            <Link
              href="/"
              className="text-brand hover:underline text-sm"
            >
              &larr; Back to SchoolSkim
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
