export default function DigestPreview() {
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="w-full max-w-md mx-auto rounded-xl shadow-2xl overflow-hidden border border-gray-200 text-left">
      {/* Header bar */}
      <div className="bg-brand px-5 py-4">
        <h3 className="text-white text-lg font-semibold m-0">
          Daily School Digest
        </h3>
        <p className="text-white/80 text-xs mt-1">{today}</p>
      </div>

      {/* Content */}
      <div className="bg-white px-5 py-4 text-sm leading-relaxed">
        <h4 className="text-base font-bold text-gray-900 mb-2">
          Action Items
        </h4>
        <ul className="space-y-1.5 mb-4 list-none p-0">
          <li className="text-gray-700">
            <span className="font-semibold">Emma</span>:{" "}
            <span className="text-brand underline">
              Sign field trip permission slip
            </span>{" "}
            — due Friday
          </li>
          <li className="text-gray-700">
            <span className="font-semibold">Liam</span>:{" "}
            <span className="text-brand underline">
              Pay lunch balance
            </span>{" "}
            — $12.50
          </li>
        </ul>

        <h4 className="text-base font-bold text-gray-900 mb-2">Coming Up</h4>
        <ul className="space-y-1.5 mb-4 list-none p-0">
          <li className="text-gray-700">
            <span className="font-semibold">Liam</span>:{" "}
            <span className="text-brand underline">Science fair</span> — April 5
          </li>
          <li className="text-gray-700">
            <span className="font-semibold">Emma</span>:{" "}
            <span className="text-brand underline">SAT prep workshop</span> —
            next Wednesday
          </li>
        </ul>

        <h4 className="text-base font-bold text-gray-900 mb-2">Quick Hits</h4>
        <ul className="space-y-1.5 list-none p-0">
          <li className="text-gray-700">
            <span className="font-semibold">Liam</span>:{" "}
            <span className="text-brand underline">Art club</span> is doing
            watercolors this week
          </li>
          <li className="text-gray-700">
            <span className="font-semibold">District</span>:{" "}
            <span className="text-brand underline">Spring break</span> reminder
            — April 14-18
          </li>
        </ul>

        <div className="text-center text-xs text-gray-400 mt-4 pt-3 border-t border-gray-100">
          Generated by SchoolSkim
        </div>
      </div>
    </div>
  );
}
